"""Document → markdown.

A dumb transformation, deliberately: no model calls, no reordering, no
summarising. All the value lives in the document, and a renderer that adds
judgement adds a second place where the output can be wrong.

Two things it must not lose in translation:

**Confidence and staleness are visible per claim.** A document whose tiers only
exist in JSON is a document whose reader treats every sentence as equally
certain, which is the failure the tiers exist to prevent.

**The capability manifest leads.** It goes at the top, before the content,
because its whole purpose is to let a reader discount what follows — and a
caveat printed after the conclusions has already failed.
"""

from __future__ import annotations

from kreb.doc.schema import Document, Section
from kreb.doc.validate import Report

CONFIDENCE_MARK = {
    "verified": "✓ verified",
    "derived": "~ derived",
    "speculative": "? speculative",
}

STALENESS_MARK = {
    "fresh": "",
    "stale": " ⚠ changed since this was written",
    "moved": " ↷ moved",
    "broken": " ✗ no longer present",
}


def render(doc: Document, report: Report | None = None) -> str:
    """Render a document as markdown, with evidence and caveats intact."""
    parts: list[str] = [f"# {doc.title}", ""]

    if doc.question:
        parts += [f"**Question:** {doc.question}", ""]

    parts += _manifest(doc)

    for section in doc.sections:
        parts += _section(section, doc, report)

    parts += _footer(doc)
    return "\n".join(parts).rstrip() + "\n"


def _manifest(doc: Document) -> list[str]:
    caps = doc.capabilities
    warnings = caps.warnings()
    lines = ["## What this document is built on", ""]
    lines.append(f"- commit `{caps.base_sha[:12]}`")
    lines.append(f"- languages indexed: {', '.join(caps.languages) or 'none'}")
    lines.append(f"- git history: {caps.git} · forge: {caps.forge} · web: {caps.web}")
    if warnings:
        lines += ["", "**Read with these limits in mind:**", ""]
        lines += [f"- {w}" for w in warnings]
    lines.append("")
    return lines


def _section(section: Section, doc: Document, report: Report | None) -> list[str]:
    lines = [f"## {section.title}", ""]

    if section.kind == "background":
        # Containment at render time beats detection. Even if a repo-scoped
        # claim slipped past validation, the reader is told what kind of
        # statement they are looking at before they read it.
        lines += ["> **About the library, not this repository.**", ""]

    lines += [f"*{CONFIDENCE_MARK.get(section.confidence, section.confidence)}*", ""]
    lines += [section.body.strip(), ""]

    if section.diagram:
        lines += _diagram(section)

    if section.anchors:
        lines += ["**Cited symbols**", ""]
        for anchor in section.anchors:
            state = report.staleness.get(anchor.ref, "fresh") if report else "fresh"
            note = STALENESS_MARK.get(state, "")
            if state == "moved" and report:
                note = f" ↷ now at `{report.moved.get(anchor.ref, '?')}`"
            location = f" (lines {anchor.lines[0]}–{anchor.lines[1]})" if anchor.lines else ""
            lines.append(f"- `{anchor.ref}`{location}{note}")
        lines.append("")

    external = [e for e in section.evidence if e.is_external]
    history = [e for e in section.evidence if e.kind in ("commit", "pull_request", "issue")]
    if history:
        lines += ["**History**", ""]
        for item in history:
            label = {"commit": "commit", "pull_request": "PR", "issue": "issue"}[item.kind]
            suffix = f" — {item.note}" if item.note else ""
            method = f" _(via {item.method})_" if item.method else ""
            lines.append(f"- {label} `{item.ref}`{suffix}{method}")
        lines.append("")
    if external:
        lines += ["**External sources**", ""]
        lines += [f"- {e.ref}" + (f" — {e.note}" if e.note else "") for e in external]
        lines.append("")

    return lines


def _diagram(section: Section) -> list[str]:
    diagram = section.diagram
    assert diagram is not None
    origin = (
        "extracted from the code"
        if diagram.provenance == "extracted"
        else "drawn from the description, not read from the code"
    )
    return [
        f"**{diagram.title}** — _{origin}_",
        "",
        "```d2",
        diagram.d2_source.strip(),
        "```",
        "",
    ]


def _footer(doc: Document) -> list[str]:
    return [
        "---",
        "",
        f"Generated by kreb at commit `{doc.capabilities.base_sha[:12]}` "
        f"on {doc.generated_at[:19].replace('T', ' ')}Z.",
        "",
        "Confidence: `verified` follows directly from cited code · `derived` is "
        "inferred from it · `speculative` is unsupported by the evidence gathered.",
    ]
